# Generated by Django 4.0.6 on 2022-08-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripOApp', '0002_rename_user_tripouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tripOApp.tripouser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tripOApp.profile'),
            preserve_default=False,
        ),
    ]
