# Generated by Django 4.0.6 on 2022-08-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripOApp', '0004_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip',
        ),
        migrations.AddField(
            model_name='profile',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tripOApp.trip'),
            preserve_default=False,
        ),
    ]
