# Generated by Django 4.0.6 on 2022-08-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripOApp', '0005_remove_trip_trip_profile_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='trip',
        ),
    ]
