# Generated by Django 4.0.6 on 2022-08-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripOApp', '0009_trip_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripOuser',
        ),
    ]
