# Generated by Django 4.0.6 on 2022-08-05 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tripOApp', '0010_delete_tripouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip',
        ),
        migrations.AddField(
            model_name='profile',
            name='trip',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tripOApp.trip'),
            preserve_default=False,
        ),
    ]
